apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - github:
        clientID: f75ef9aaf2797a7b53c6
        clientSecret:
          name: github-client-secret
        hostname: ''
        organizations:
          - baloise-incubator
        teams: []
      mappingMethod: claim
      name: github
      type: GitHub
