apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-client-secret
spec:
  data:
    - remoteRef:
        key: /cloudflare/api-key
      secretKey: clientSecret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    deletionPolicy: Delete