apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-client-secret
  namespace: openshift-config
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /github/clientSecret
        metadataPolicy: None
      secretKey: clientSecret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    creationPolicy: Owner
    deletionPolicy: Delete