apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-client-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgCLgIDbERfJPdnVRYD2195ZbNGjETxdzHN+8NqNQvXhjmb6JhxMBpd1KEp7bCBqb1yZnyUxRY0U/bDFsHwfHmnEmOtdiRoaKpJde5hmqHDWq4K2pRtrt/NgOhvQeQSlUkTbadw/Kich6jpcH2Oe4s0w0d/n1u4cDNfLVZTUBsXMUWV5X45pmZo+5oLeUJCiP5SGvit80p6DXzy9p1l4hqXoms9gwbCGi/xJ+DgS5ttL1+TsTpGDSq82nuJmCOmHKwC3wFiKOYKqMMMhhI2I7S5ceCj5EoXJRSZeQ9GTTWsXy2Q4ouavz20+u5i+9T7R0XmFxdzWEiQAy1cT+4eoGwcjEopg7d2hW5xj7BuvZR3u43XJLLZGRtcp3zuM4iYRZTGTNOe9XSZlOLSxv7+qXx0NZvyqSK9LfwUkCFu6muEJibQ0G83rnZLM6iNyp9fcBjQHHbo1GGQz9fdM5MC1kaUrwlPXcTI3w7D60ehlf8WmtvBHcSL2zyiedLCR/KK0lTMYRpuNjLBEibcVYUS78ar/dsTCpcOL8K5n7A/qUdHVHeG5/SAjgsJ0It9abgxMdA0BUHNsOK/KlEglGTDgcfSpm04OUSXQ4O36ao+mm868K9yN4SPZqK+HpG2pFqA18utzxoV03gd9jXETJep0fu99qtXwQvHvRVXK7I32ncR4r06wYVw4B0E6Qw9hOn59xLrIt8Ol2SyALhVw7LpJR76jWCI7COcZrmIAmhLfKdRK+om6SUnAgZcd
  template:
    metadata:
      creationTimestamp: null
      name: github-client-secret
      namespace: openshift-config
    type: Opaque

