apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: cluster-admins
users:
  - niiku
  - CookieMonster70
  - christiansiegel
  - danielgrob
  - joachimprinzbach
  - mbobzin
  - leubedane
  - luechtdiode
  - patrit
  - yannickholzenkamp
  - mikevader
  - tiliavir
  - renat1sakenov
  - mebagel
  - dweber019
  - gerohoff
  - niels-oz
  - hannah-mat
  - MarkusFlorian79
  - henriks23
  - marcschmidlin
  - makrelas
  - koenigle
  - robert-groensfeld
  - tschei65
  - jonasz-lasut-baloise
  - Kacper08480
  - StephanSST
