apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: cluster-admins
users:
  - niiku
  - CookieMonster70
  - christiansiegel
  - danielgrob
  - joachimprinzbach
  - mbobzin
  - leubedane
  - luechtdiode
  - patrit
  - yannickholzenkamp
  - mikevader
  - tiliavir
  - renat1sakenov
  - mabegglen
  - dweber019
  - gerohoff
